version: '3.8'

services:
  # Standalone Valkey server for basic testing
  valkey-standalone:
    image: valkey/valkey:latest
    container_name: valkey-standalone-test
    ports:
      - "${VALKEY_STANDALONE_PORT:-6379}:6379"
    command: valkey-server --bind 0.0.0.0 --protected-mode no
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - valkey-test-network

  # Valkey cluster nodes
  valkey-cluster-1:
    image: valkey/valkey:latest
    container_name: valkey-cluster-1
    ports:
      - "${VALKEY_CLUSTER_PORT_1:-7000}:7000"
    command: |
      sh -c "
        valkey-server --port 7000 \
        --cluster-enabled yes \
        --cluster-config-file nodes-7000.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --bind 0.0.0.0 \
        --protected-mode no
      "
    networks:
      - valkey-test-network

  valkey-cluster-2:
    image: valkey/valkey:latest
    container_name: valkey-cluster-2
    ports:
      - "${VALKEY_CLUSTER_PORT_2:-7001}:7000"
    command: |
      sh -c "
        valkey-server --port 7000 \
        --cluster-enabled yes \
        --cluster-config-file nodes-7001.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --bind 0.0.0.0 \
        --protected-mode no
      "
    networks:
      - valkey-test-network

  valkey-cluster-3:
    image: valkey/valkey:latest
    container_name: valkey-cluster-3
    ports:
      - "${VALKEY_CLUSTER_PORT_3:-7002}:7000"
    command: |
      sh -c "
        valkey-server --port 7000 \
        --cluster-enabled yes \
        --cluster-config-file nodes-7002.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --bind 0.0.0.0 \
        --protected-mode no
      "
    networks:
      - valkey-test-network

  valkey-cluster-4:
    image: valkey/valkey:latest
    container_name: valkey-cluster-4
    ports:
      - "${VALKEY_CLUSTER_PORT_4:-7003}:7000"
    command: |
      sh -c "
        valkey-server --port 7000 \
        --cluster-enabled yes \
        --cluster-config-file nodes-7003.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --bind 0.0.0.0 \
        --protected-mode no
      "
    networks:
      - valkey-test-network

  valkey-cluster-5:
    image: valkey/valkey:latest
    container_name: valkey-cluster-5
    ports:
      - "${VALKEY_CLUSTER_PORT_5:-7004}:7000"
    command: |
      sh -c "
        valkey-server --port 7000 \
        --cluster-enabled yes \
        --cluster-config-file nodes-7004.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --bind 0.0.0.0 \
        --protected-mode no
      "
    networks:
      - valkey-test-network

  valkey-cluster-6:
    image: valkey/valkey:latest
    container_name: valkey-cluster-6
    ports:
      - "${VALKEY_CLUSTER_PORT_6:-7005}:7000"
    command: |
      sh -c "
        valkey-server --port 7000 \
        --cluster-enabled yes \
        --cluster-config-file nodes-7005.conf \
        --cluster-node-timeout 5000 \
        --appendonly yes \
        --bind 0.0.0.0 \
        --protected-mode no
      "
    networks:
      - valkey-test-network

  # Cluster setup service
  valkey-cluster-setup:
    image: valkey/valkey:latest
    container_name: valkey-cluster-setup
    depends_on:
      - valkey-cluster-1
      - valkey-cluster-2
      - valkey-cluster-3
      - valkey-cluster-4
      - valkey-cluster-5
      - valkey-cluster-6
    command: |
      sh -c "
        sleep 10
        echo 'Setting up Valkey cluster...'
        valkey-cli --cluster create \
          valkey-cluster-1:7000 \
          valkey-cluster-2:7000 \
          valkey-cluster-3:7000 \
          valkey-cluster-4:7000 \
          valkey-cluster-5:7000 \
          valkey-cluster-6:7000 \
          --cluster-replicas 1 \
          --cluster-yes
        echo 'Cluster setup complete!'
        sleep infinity
      "
    networks:
      - valkey-test-network

networks:
  valkey-test-network:
    driver: bridge