version: '3.8'
services:
  valkey-node-7000:
    image: valkey/valkey:latest
    command: >-
      valkey-server --port 7000 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly no --protected-mode no
      --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7000 --cluster-announce-bus-port 17000
    ports:
      - "7000:7000"
      - "17000:17000"
    restart: unless-stopped

  valkey-node-7001:
    image: valkey/valkey:latest
    command: >-
      valkey-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly no --protected-mode no
      --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7001 --cluster-announce-bus-port 17001
    ports:
      - "7001:7001"
      - "17001:17001"
    restart: unless-stopped

  valkey-node-7002:
    image: valkey/valkey:latest
    command: >-
      valkey-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly no --protected-mode no
      --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7002 --cluster-announce-bus-port 17002
    ports:
      - "7002:7002"
      - "17002:17002"
    restart: unless-stopped

  valkey-node-7003:
    image: valkey/valkey:latest
    command: >-
      valkey-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly no --protected-mode no
      --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7003 --cluster-announce-bus-port 17003
    ports:
      - "7003:7003"
      - "17003:17003"
    restart: unless-stopped

  valkey-node-7004:
    image: valkey/valkey:latest
    command: >-
      valkey-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly no --protected-mode no
      --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7004 --cluster-announce-bus-port 17004
    ports:
      - "7004:7004"
      - "17004:17004"
    restart: unless-stopped

  valkey-node-7005:
    image: valkey/valkey:latest
    command: >-
      valkey-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly no --protected-mode no
      --cluster-announce-ip 127.0.0.1 --cluster-announce-port 7005 --cluster-announce-bus-port 17005
    ports:
      - "7005:7005"
      - "17005:17005"
    restart: unless-stopped

  cluster-create:
    image: valkey/valkey:latest
    depends_on:
      - valkey-node-7000
      - valkey-node-7001
      - valkey-node-7002
      - valkey-node-7003
      - valkey-node-7004
      - valkey-node-7005
    network_mode: host
    entrypoint: /bin/sh
    command: -lc "set -e; for i in $(seq 1 30); do nc -z 127.0.0.1 7000 && nc -z 127.0.0.1 7001 && nc -z 127.0.0.1 7002 && nc -z 127.0.0.1 7003 && nc -z 127.0.0.1 7004 && nc -z 127.0.0.1 7005 && break || sleep 2; done; yes yes | valkey-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-replicas 1 || true; for i in $(seq 1 30); do valkey-cli -p 7000 cluster info | grep -q 'cluster_state:ok' && exit 0 || sleep 2; done; valkey-cli -p 7000 cluster info; exit 1"
    restart: "no"
